### ISSUE TITLE
Error: java.lang.UnsupportedOperationException: empty.head - when I try to run the compiled binary

### ISSUE THREAD

**Issue by elmbeech** [ryants/EstCC#4]
Dear Ryan, 

I successfully compiled EstCC with
+ java version 1.8.0_131, 
+ scala version 2.12.2,
+ sbt 0.13.15.

And try to run `java -jar estcc.jar -d datafile.tsv`.

My `datafile.tsv` file contains first a `signalColumns` then a `<tab>` then a`responseColumns`, as I assume it is specified in the `InfConfig.scale` file:
```scala
/** Parameters that have list/tuple values. */
  val listParams: Map[String, List[Double]] =
    Map("signalColumns" -> List(0.0),
      "responseColumns" -> List(1.0),
      "biPeakWeights" -> List(0.4, 0.5, 0.6),
      "sigBinSpacing" -> List(4),
"respBinSpacing" -> List(4))
```

The first  and last some rows of the `datafile.tsv` file for example look like this:  
```
40      26.02200347
40      24.84076433
40      23.91816252
...
0       101.0415656
0       101.0480349
```

I don't see what I do possibly wrong.
However, I get the the following error log:
```
me@mycomputer:~/prj/estcc$ java -jar estcc.jar -d datafile.tsv
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.UnsupportedOperationException: empty.head
        at scala.collection.immutable.Vector.head(Vector.scala:193)
        at infcalcs.EstimateMI$.optMIMult(InfMethods.scala:605)
        at infcalcs.EstimateCC$.estimateCC(InfMethods.scala:1011)
        at infcalcs.EstCC$.delayedEndpoint$infcalcs$EstCC$1(EstCC.scala:63)
        at infcalcs.EstCC$delayedInit$body.apply(EstCC.scala:22)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at infcalcs.EstCC$.main(EstCC.scala:22)
        at infcalcs.EstCC.main(EstCC.scala)
        ... 6 more
```
Frankly I am not sure if it is the code or my input that causes the error, as I am not so familiar with scala and java.
I really would like to get your software running. Any help how I could overcome this error would be appreciated.

Thank you, 
Elmar

**Comment by ryants** [comment]
Hi Elmar,

I'm attempting to reproduce the error as we speak (waiting for my Java update).  You mentioned that you used scala 2.12.2.  Did you change the scalaVersion variable in the build.sbt file and update the dependencies?  If not, you probably built it with scala 2.11.7 which should be fine (just want to try to get this error using the same system configuration).  

Also, what OS are you using?  If it's Windows, maybe there's an issue with the data file reader handling the carriage return character.  

Finally, did the program run for awhile and then crash, or did it stop immediately?  I'd also suggest using the -v flag, as that will print information about the calculation to stdout, and perhaps help in the debugging

Once I have my environment as close as possible to yours, I'll give you an update

Ryan

**Comment by elmbeech** [comment]
wow. this is a fast reply.

I did not change anything in the build.sbt file.
just followed your installation description: `run sbt one-jar in the project's root directory`
the program stops immediately. see below the output with the -v flag. 

I am running  macOS Sierra 10.12.5 with Xcode version 8.3.2 (this is the basic OS, latest version).
All dependencies: java, scala and  sbt I have installed with homebrew 1.2.2 (is is kind of a package manager for mac os x.  similar to apt-get in debian.) 

an amazing paper you wrote! I really enjoyed to read it.

```
me@mycomputer:~/prj/estcc$ java -jar estcc.jar -v -d experiment38_estcc_input_datafile.tsv

Verbose mode

responseColumns 1.0
respBinSpacing  4.0
sigBinSpacing   4.0
biPeakWeights   0.4, 0.5, 0.6
signalColumns   0.0

numConsecRandPos        3.0
lowFraction     0.6
uniSigmaNumber  5.0
biSigmaNumber   5.0
cutoffValue     0.0
numFractions    5.0
repsPerFraction 20.0
numRandom       10.0
avgEntriesPerBin        0.0
numConsecBiasedSigEst   3.0
numForCutoff    1.0
biMuNumber      5.0
uniMuNumber     5.0

logSpace        false
outputRegData   false
uniformWeight   true
pwUniformWeight false

directory       ./
filePrefix      out

responseValues  None
signalValues    None


Results:

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.simontuffs.onejar.Boot.run(Boot.java:340)
        at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.UnsupportedOperationException: empty.head
        at scala.collection.immutable.Vector.head(Vector.scala:193)
        at infcalcs.EstimateMI$.optMIMult(InfMethods.scala:605)
        at infcalcs.EstimateCC$.estimateCCVerbose(InfMethods.scala:948)
        at infcalcs.EstCC$.delayedEndpoint$infcalcs$EstCC$1(EstCC.scala:62)
        at infcalcs.EstCC$delayedInit$body.apply(EstCC.scala:22)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.
```

**Comment by ryants** [comment]
Glad you liked the paper!

So far I haven't been able to reproduce the issue with my own mock data sets (which are just files of random numbers using numpy.savetxt with a tab delimiter).  I don't have a machine with macOS Sierra (I'm using El Capitan still), but I'm using the same versions of everything else.  

Would you be willing to attach one of the datafiles you've been working with?  From your description the format looks correct, but I'm not sure what else could be causing this issue

**Comment by elmbeech** [comment]
[experiment38_estcc_input_datafile.txt](https://github.com/ryants/EstCC/files/1056554/experiment38_estcc_input_datafile.txt)

I attached a cut down version (16 values per signal) of the input file that causes the error too.
the command I execute looks like this: 
` java -jar estcc.jar -d experiment38_estcc_input_datafile.txt`.
As you can see, I renamed  `estcc_2.11-0.1-SNAPSHOT-one-jar.jar` to `estcc.jar`.

It is as well not a permission issue. I chmod 777 estcc.jar and datafile and the error still happens.

I would be surprised if you can reproduce the error now.
I have an old mac,  running still mountain lion,  at home. will try to get EstCC running there, this evening.
maybe it is really the OS.

**Comment by ryants** [comment]
Ok, I got the error with this data set.  I'll let you know when I get it worked out

**Comment by ryants** [comment]
So the issue was an undocumented and untested edge case where the default configuration caused the calculation to crash.  I'll be pushing a brief explanation in the README and a few changes that should handle this case a bit more explicitly, but here's what happened and how to avoid it:

This method uses an estimation approach that relies on sampling subsets of the original data set.  These subsamples are then binned into what is essentially a 2-D histogram.  The default behavior of the program is to search for an appropriate number of bins for each dimension.  One constraint of this process is to make sure that the number of bins in a particular dimension is always less than the number of unique values in the data set for that dimension times the smallest fraction of the original data set that will be sampled.  In your case, this constraint is broken immediately, as the data set has 4 unique values in the first column and the program's default behavior sets the initial number of bins to 4 and the minimum subsampling fraction to 0.6.  This particular constraint is implemented to prevent potential statistical artifacts from creeping into the results.

This can be avoided in two ways.  First, the initial number of bins (and the spacing between attempted bin numbers during the iterative searching process) can be lowered all the way to 1 using the sigBinSpacing or respBinSpacing parameters.  Second (and probably more useful) you can override the default behavior by specifying the set of unique values for a particular dimension if they are known.  In your example data file, there are 4 unique values in the first column, so you could introduce a configuration file that assigns the signalVals1 parameter to be that set of values.  This will also drastically decrease calculation time as you will only be searching bin space in one dimension (your second column).  Attached is a parameter file that should help.  You can use either of the listed parameters in the file (deleting or commenting the other with a '#') and the signalVals1 parameter will override the sigBinSpacing parameter if both are left in.

[parameter_config.txt](https://github.com/ryants/EstCC/files/1056827/parameter_config.txt)

Just use the -p flag followed by the configuration file name:

`java -jar estcc.jar -v -d data.txt -p config.txt`

If any of this is unclear (or if it still doesn't work with the config file), please let me know!

Ryan

**Comment by elmbeech** [comment]
Dear Ryan,

Thank you very much for this detailed explanation!
Now the code runs.

It is absolutely true. I know what I signal and what I receive is what I measure.
I understand that I like this can calculate the mutual information.
But i thought the problem to detect the channel capacity is that I have to find from all possible signaling distribution the one that enforces the maximal mutual information. 
So it might really well be that I not even signal with the bins that cause the maximal mutual information. When I now set signalVals1 to the 4 input values, do I then not restrict my alphabet to this 4 characters. 
I think I have now to dig deeper into the supplementary information of the paper understand all your parameters. Frankly I have not yet read the supplementary part of your paper. 
From Raymond Cheong's paper I remember that the "plateau region" helped to find the most reliable number of bins and the Arimoto-Blahut algorithm helped to find the maximal mutual information. And I assume you do something similar. 

Above all, thank you very much helping me to getting the code running!
I am sure I will soon understand more. 
Best Wishes, Elmar

**Comment by ryants** [comment]
Regarding setting signalVals1 to the input values, yes the calculation is restricted, but that is a restriction of the data.  The binning procedure in our application doesn't try to infer anything about signal space, but simply tries to find an appropriate discretization of the space.  Even if we hadn't implemented the constraint that caused these issues, the maximum number of bins potentially selected by the algorithm would be the number of unique signal values.  

In order to estimate the channel capacity we simply apply a series of weights (essentially probability mass functions) along the signal dimension of the binned data.  This is described in the supplement, but please feel free to contact me or Eric (the corresponding author on the paper) if you have any more questions about the calculation!

Ryan
